version: '3.0'

rpc:
    listen: tcp://0.0.0.0:6001

server:
    command: "php app.php"
    relay: pipes

logs:
    level: info

jobs:
    consume: [ ]
    pool:
        num_workers: 2
        supervisor:
            max_worker_memory: 100

grpc:
    listen: "tcp://0.0.0.0:9000"
    pool:
        num_workers: 5
    proto:
        - "./proto/api/payment/v1/service.proto"

metrics:
    address: 0.0.0.0:2112
    collect:
        total_transactions:
            type: counter
            help: "Total transactions"
        money_sum:
            type: counter
            help: "Total money"
        money_fee_sum:
            type: counter
            help: "Total fee"

status:
    address: 127.0.0.1:2114
    unavailable_status_code: 503

otel:
    insecure: true
    compress: false
    client: http
    exporter: otlp
    service_name: rr-payment
    service_version: 1.0.0
    endpoint: collector:4318
