version: '3.0'

rpc:
    listen: tcp://0.0.0.0:6001

logs:
    level: debug

server:
    command: "php app.php"
    relay: pipes

temporal:
    address: temporal:7233
    activities:
        num_workers: 5

jobs:
    consume: [ "test" ]
    pipelines:
        test:
            driver: memory
            config:
                priority: 10
                prefetch: 10

grpc:
    listen: "tcp://0.0.0.0:9000"
    pool:
        num_workers: 5
    proto:
        - "./proto/api/cinema/v1/service.proto"

centrifuge:
    grpc_api_address: "centrifugo:10000"
    version: "1.0.0"

metrics:
    address: 0.0.0.0:2112
    collect:
        tickets_reservation:
            type: gauge
            help: "Ticket reservations"
            labels: [ 'movie', 'auditorium', 'price' ]
        reservations:
            type: counter
            help: "Total reservations"
        canceled_reservations:
            type: counter
            help: "Canceled reservations"

status:
    address: 127.0.0.1:2114
    unavailable_status_code: 503

otel:
    insecure: true
    compress: false
    client: http
    exporter: otlp
    service_name: rr-cinema
    service_version: 1.0.0
    endpoint: collector:4318
